/** Editorial pages: /how-it-works and /terms. Same navbar, footer, fonts and colours as the rest of the site. */
import { escapeHtml } from '../html';
import { page } from './layout';
import { WF_PAGE_IDS, footer, navbar } from './partials';

export const TERMS_UPDATED = '3 October 2026';

export interface PageShellOptions {
  eyebrow: string;
  title: string;
  lead: string;
  body: string;
  /** Rendered inside the hero on the right (e.g. a product tile). */
  heroAside?: string;
}

/** Hero + content container used by the editorial pages and the blog. */
export function pageShell(opts: PageShellOptions): string {
  return `${navbar('logo-left')}
  <main class="ww-page-wrap">
    <header class="ww-page-hero${opts.heroAside ? ' has-aside' : ''}">
      <div class="ww-page-hero-text">
        <div class="ww-eyebrow">${escapeHtml(opts.eyebrow)}</div>
        <h1 class="ww-page-title">${escapeHtml(opts.title)}</h1>
        <p class="ww-page-lead">${escapeHtml(opts.lead)}</p>
      </div>${opts.heroAside ?? ''}
    </header>
    <div class="ww-page">${opts.body}
    </div>
  </main>${footer()}`;
}

export function quizCta(title = 'Ready for your own list?', text = 'Two minutes, no account, free. The advisor only suggests what fits your answers.'): string {
  return `
      <aside class="ww-cta">
        <div>
          <h3>${escapeHtml(title)}</h3>
          <p>${escapeHtml(text)}</p>
        </div>
        <a href="/wellness-quiz" class="footerbutton w-inline-block"><div class="text-57">Start Quiz Now</div></a>
      </aside>`;
}

export function faqHtml(items: readonly { q: string; a: string }[]): string {
  if (!items.length) return '';
  return `
      <section class="ww-faq">
        <h2>Frequently asked questions</h2>
        ${items.map((f) => `<details><summary>${escapeHtml(f.q)}</summary><p>${escapeHtml(f.a)}</p></details>`).join('\n        ')}
      </section>`;
}

// ---------- How it works ----------

const HOW_FAQ = [
  { q: 'Is Wellness Whizz free?', a: 'Yes. The quiz, the results page and every supplement page are free, and there is no account to create. We are paid a small commission by iHerb when you buy through our links, at no extra cost to you.' },
  { q: 'Why iHerb?', a: 'iHerb carries most of the brands in our catalogue, ships to more than 180 countries, publishes third-party testing information and prices in local currencies. Our referral partnership with iHerb is what keeps the advisor free.' },
  { q: 'Can I trust advice generated by AI?', a: 'Treat it as a well-organised starting point, not a prescription. The advisor works from a structured catalogue with safety ratings and known interactions, but it can still be wrong or miss something about you. Read the contraindications on each supplement page and check with a pharmacist or doctor, especially if you are pregnant, take medication or live with a chronic condition.' },
  { q: 'Do you store my answers?', a: 'Your quiz answers are stored so that your results page keeps working, but they are not linked to your name or email, and we do not sell them. See the Terms and Conditions for the details.' },
  { q: 'What if the advisor suggests something that is not in the catalogue?', a: 'When your answers call for a supplement we have not profiled yet, the advisor writes a new profile with the same structure, ratings and warnings as the rest of the catalogue, and it joins the catalogue for everyone.' },
];

export function renderHowItWorks(catalogueSize: number): string {
  const n = catalogueSize >= 50 ? `${Math.floor(catalogueSize / 10) * 10}+` : 'our';
  const body = `
      <section class="ww-steps">
        <div class="ww-step"><b>1</b><h3>Tell us about you</h3><p>Answer a few questions about your goals, diet, lifestyle, health conditions and the supplements you already take. It takes about two minutes and you do not need an account.</p></div>
        <div class="ww-step"><b>2</b><h3>The advisor checks the catalogue</h3><p>Your answers are compared with a curated catalogue of ${escapeHtml(n)} supplements. Every entry carries a safety rating, FDA status, an effectivity score and notes on interactions, so the advisor can rule out what does not fit before it ranks what does.</p></div>
        <div class="ww-step"><b>3</b><h3>You get a short, explained list</h3><p>Instead of a hundred options you get three to five. Each comes with a one-paragraph reason written for your answers, product picks, and a link to the full supplement page.</p></div>
        <div class="ww-step"><b>4</b><h3>Buy with confidence</h3><p>Every recommendation links to matching products on iHerb, a retailer that ships worldwide and publishes third-party testing. We earn a small commission on purchases made through our links; you pay the same price.</p></div>
      </section>
      <section class="ww-prose">
        <h2>What every supplement page tells you</h2>
        <p>Each supplement in the catalogue has its own page, written to answer the questions people actually have before they buy:</p>
        <ul>
          <li><strong>Benefits and contraindications</strong>: what the supplement is used for, and who should avoid it or ask a doctor first.</li>
          <li><strong>Effectivity and safety ratings</strong>: two five-point scales, explained below, plus the FDA status of the ingredient.</li>
          <li><strong>How it works with other supplements</strong>: combinations that enhance each other and combinations that interact.</li>
          <li><strong>Holistic Highlights</strong>: a longer article on how it works, who benefits most, how to take it and how it fits into sleep, diet and training.</li>
          <li><strong>Relevant studies</strong>: links to the peer-reviewed research behind the claims, so you can read the evidence yourself.</li>
          <li><strong>Product picks</strong>: a short list of well-reviewed products on iHerb, with photos and direct links.</li>
        </ul>
        <h2>How we rate</h2>
        <h3>Effectivity (1 to 5)</h3>
        <p>How strong and consistent the evidence is for the supplement's main uses. A 5 means several good-quality human trials or meta-analyses point the same way (creatine for strength, for example). A 1 or 2 means the evidence is early, mixed or mostly from animal studies. The score describes the research, not how you personally will respond.</p>
        <h3>Safety (1 to 5)</h3>
        <p>How much caution the supplement calls for at typical doses in healthy adults. A 5 ("safe") has a long record of use and few interactions. Lower scores mean there are meaningful interactions, side effects at common doses, or groups of people who should not take it. Supplements marked "prescription" are not sold over the counter in most countries.</p>
        <h3>FDA status</h3>
        <p>Whether the ingredient is approved or generally recognised as safe by the US Food and Drug Administration, is on the market without a specific approval, or has been the subject of an FDA warning. Dietary supplements are regulated differently from medicines, so "not approved" does not automatically mean unsafe, and "approved" does not mean effective. We show it because it is a useful, verifiable signal.</p>
        <h2>What we are not</h2>
        <p>Wellness Whizz is an information tool. It is not a medical service, the advisor is not a doctor, and nothing on this site is a diagnosis or a treatment plan. Artificial intelligence can be confidently wrong. Please read the contraindications on each page, check your medication with a pharmacist, and talk to a doctor before starting anything new if you are pregnant or breastfeeding, under 18, or managing a health condition.</p>
        <h2>Your privacy</h2>
        <p>There is no account. Your quiz answers are stored so your results page keeps working, without your name or email. We keep a hashed version of your IP address for a short time to prevent abuse, and we count page views and outbound clicks without personal identifiers. The full picture is in our <a href="/terms">Terms and Conditions</a>.</p>
      </section>${quizCta()}${faqHtml(HOW_FAQ)}`;

  const body2 = pageShell({
    eyebrow: 'How it works',
    title: 'Personal supplement advice, built on evidence',
    lead: 'Wellness Whizz turns a two-minute questionnaire into a short list of supplements that fit your goals, diet and safety profile, with links to buy each one on iHerb.',
    body,
  });
  return page({
    title: 'How it works',
    description: 'How Wellness Whizz turns a two-minute quiz into a short, explained list of supplements with safety ratings, evidence scores and iHerb product picks.',
    pageId: WF_PAGE_IDS.supplement,
    bodyClass: 'body-2',
    body: body2,
  });
}

// ---------- Terms and Conditions ----------

export function renderTerms(): string {
  const body = `
      <section class="ww-prose ww-legal">
        <p class="ww-legal-updated">Last updated: ${TERMS_UPDATED}</p>
        <h2>1. Who we are and what you agree to</h2>
        <p>Wellness Whizz ("Wellness Whizz", "we", "us") operates this website and the AI supplement advisor on it (together, the "Service"). By using the Service you agree to these Terms and Conditions, including the privacy section below. If you do not agree, please do not use the Service.</p>
        <h2>2. What the Service is</h2>
        <p>The Service is an information tool. It asks you questions about your goals and lifestyle, compares your answers with a catalogue of dietary supplements, and shows you a short list of supplements with explanations, ratings, articles and links to products sold by third-party retailers, principally iHerb. Much of the content, including the recommendations, supplement profiles and articles, is generated or assisted by artificial intelligence.</p>
        <h2>3. Not medical advice</h2>
        <p>Nothing on the Service is medical advice, a diagnosis or a treatment. The Service does not create a doctor-patient relationship. Dietary supplements can interact with medicines and medical conditions, and the right choice depends on facts about you that a questionnaire cannot capture. Always read product labels and consult a qualified healthcare professional before starting, stopping or combining supplements, in particular if you are pregnant or breastfeeding, under 18, take medication or live with a health condition. In an emergency, contact your local emergency services.</p>
        <h2>4. Accuracy of AI-generated content</h2>
        <p>We take care over the structure of our catalogue, but AI-generated text can contain errors, omissions or statements that are out of date. Effectivity and safety ratings and FDA status indicators are editorial estimates intended as a starting point, not a guarantee. Product names, prices, availability and label information belong to the retailer and the manufacturer and may change without notice. Verify anything that matters to you before you rely on it.</p>
        <h2>5. Affiliate disclosure</h2>
        <p>Wellness Whizz takes part in the iHerb Rewards program. Links to iHerb on this site carry our referral code, and we earn a commission when you buy through them. You pay the same price as you would without the code. Commissions do not change which supplements the advisor recommends; product links are chosen for relevance to the supplement being described. Links to other services, such as ChatGPT or TikTok, are not affiliate links.</p>
        <h2>6. Using the Service</h2>
        <p>You may use the Service for your own, non-commercial purposes. You agree not to misuse it, which includes sending automated requests, scraping or copying the catalogue at scale, attempting to interfere with the Service's operation or security, or using it to generate content for resale. We may limit the number of requests from a single network, and we may suspend or restrict access to protect the Service.</p>
        <h2>7. Your responsibilities</h2>
        <p>The quality of the advice depends on the accuracy of your answers. You are responsible for the decisions you make based on the Service, for reading labels and warnings, and for checking with a healthcare professional. You confirm that you are at least 18 years old, or are using the Service with the involvement of a parent or guardian.</p>
        <h2>8. Intellectual property</h2>
        <p>The design, text, illustrations, software and the Wellness Whizz name and logo are owned by us or our licensors and are protected by copyright and other laws. Product names, brand names and product photographs belong to their respective owners and are shown to identify the products. You may view and print pages for personal use. Any other use needs our written permission.</p>
        <h2>9. Third-party websites</h2>
        <p>The Service links to websites we do not control, including iHerb. Those sites have their own terms and privacy policies, and we are not responsible for their content, products, prices, shipping, returns or data practices. A purchase you make on a third-party site is a contract between you and that site.</p>
        <h2>10. Privacy</h2>
        <h3>What we collect</h3>
        <ul>
          <li><strong>Quiz answers.</strong> The answers you give are stored together with a random results identifier so that your results page keeps working and can be shared by link. They are not linked to your name, email or account; there are no accounts.</li>
          <li><strong>A hashed IP address.</strong> To prevent abuse we store a one-way hash of your network address with each quiz submission for a limited time. It cannot be reversed into your address.</li>
          <li><strong>Usage events.</strong> We count page views, quiz starts, results views and clicks on product links. These counts are not tied to your identity.</li>
          <li><strong>Advertising measurement.</strong> The site loads the Google Ads tag, which may set cookies to measure whether our advertising brought you here. You can block or delete cookies in your browser; the Service works without them.</li>
        </ul>
        <h3>What we do not do</h3>
        <p>We do not sell personal data, we do not run accounts or newsletters without your explicit opt-in, and we do not share your quiz answers with retailers. When you click through to iHerb, iHerb's own privacy policy applies from that point on.</p>
        <h3>Retention and your rights</h3>
        <p>Results pages and the answers behind them are kept so that shared links continue to work. If you would like a results page deleted, contact us through the channels linked in the footer and tell us the link; we will remove it. Depending on where you live you may have further rights over personal data, such as access or erasure, which you can exercise the same way.</p>
        <h2>11. Disclaimer of warranties</h2>
        <p>The Service is provided "as is" and "as available", without warranties of any kind, express or implied, including fitness for a particular purpose, accuracy and non-infringement. We do not promise that the Service will be uninterrupted, error-free or that its content will be correct, complete or current.</p>
        <h2>12. Limitation of liability</h2>
        <p>To the fullest extent permitted by law, Wellness Whizz and the people who work on it are not liable for any indirect, incidental, special, consequential or punitive damages, or for any loss of health, profit, data or goodwill, arising from your use of or inability to use the Service, from any content on it, or from any product you buy through it. Where liability cannot be excluded, it is limited to the amount you paid us to use the Service, which is nothing. Nothing in these terms limits liability that cannot be limited under the law that applies to you.</p>
        <h2>13. Indemnity</h2>
        <p>You agree to hold us harmless from claims, losses and expenses, including reasonable legal fees, that arise from your misuse of the Service or your breach of these terms.</p>
        <h2>14. Changes</h2>
        <p>We may update the Service and these terms. The date at the top shows the latest version. Continued use after a change means you accept the new terms. Material changes to the privacy section will be announced on this page.</p>
        <h2>15. Governing law</h2>
        <p>These terms are governed by the laws of the country in which Wellness Whizz is established, without regard to conflict-of-law rules. If you are a consumer, mandatory consumer-protection rules of your country of residence still apply. Disputes that cannot be settled amicably will be brought before the competent courts of that country.</p>
        <h2>16. Contact</h2>
        <p>Questions about these terms, a results page you would like deleted, or a correction to a supplement page can be sent through the contact channels linked in the footer of every page.</p>
      </section>`;

  const shell = pageShell({
    eyebrow: 'Legal',
    title: 'Terms and Conditions',
    lead: 'What you can expect from Wellness Whizz, what we expect from you, how we make money and what happens with your data. Written to be read, not skimmed.',
    body,
  });
  return page({
    title: 'Terms and Conditions',
    description: 'Terms of use, medical disclaimer, affiliate disclosure and privacy practices of Wellness Whizz, the AI supplement advisor.',
    pageId: WF_PAGE_IDS.supplement,
    bodyClass: 'body-2',
    body: shell,
  });
}
