// Generates seed.sql from scripts/seed-data.mjs.  Usage: node scripts/build-seed.mjs
import { writeFileSync } from 'node:fs';
import { listHtml, productUrl, studiesHtml, supplementInsert } from './lib.mjs';
import { SUPPLEMENTS } from './seed-data.mjs';

const statements = SUPPLEMENTS.map((s) =>
  supplementInsert({
    ...s,
    benefits_html: listHtml(s.benefits, 'ol'),
    contraindications_html: listHtml(s.contraindications, 'ol'),
    enhancing_html: listHtml(s.enhancing, 'ol'),
    interactions_html: listHtml(s.interactions, 'ol'),
    holistic_html: listHtml(s.holistic, 'ul'),
    studies_html: studiesHtml(s.studies),
    products: s.products.map(([name, brand]) => ({ name, brand, url: productUrl(`${brand} ${name}`) })),
  }),
);

const out = `-- Generated by scripts/build-seed.mjs — do not edit by hand, edit scripts/seed-data.mjs instead.\n${statements.join('\n\n')}\n`;
writeFileSync(new URL('../seed.sql', import.meta.url), out);
console.log(`seed.sql written with ${statements.length} supplements`);
