// Starter content so the home page, slider and "Explore manually" list are not empty on a fresh database.
// Replace or extend with your own Webflow CMS export (see scripts/import-webflow-csv.mjs).
export const SUPPLEMENTS = [
  {
    name: 'Vitamin D3', category: 'Vitamin', form_type: 'softgel', fda_status: 'approved', safety_status: 'safe', effectivity: 4, safety: 4,
    summary: 'The sunshine vitamin: supports bone health, immune function and mood, especially when sun exposure is limited.',
    benefits: ['Supports calcium absorption and bone density', 'Contributes to normal immune function', 'May support mood during darker months', 'Helps maintain muscle strength in older adults', 'Often low in people who work indoors or live far from the equator'],
    contraindications: ['Hypercalcaemia or hyperparathyroidism', 'Sarcoidosis and other granulomatous diseases', 'Kidney stones or advanced kidney disease: medical advice first', 'Very high doses (above 4000 IU daily) without blood tests'],
    enhancing: ['Take with a meal containing fat', 'Combine with vitamin K2 and magnesium', 'Get 10 to 20 minutes of midday daylight when possible', 'Test 25(OH)D levels after 3 months'],
    interactions: ['Thiazide diuretics (calcium levels)', 'Corticosteroids reduce absorption', 'Orlistat and cholestyramine reduce absorption', 'Digoxin: monitor calcium'],
    why_consider: 'Low vitamin D status is one of the most common nutrient shortfalls worldwide, particularly in winter and for people who spend most of the day indoors. Supplementing a moderate daily dose is inexpensive, well studied and easy to monitor with a blood test.',
    holistic: ['Daylight exposure and outdoor movement remain the primary source', 'Fatty fish, egg yolks and fortified foods contribute', 'Bone health also depends on resistance training', 'Re-test levels seasonally rather than guessing'],
    studies: [
      { title: 'Vitamin D supplementation to prevent acute respiratory tract infections: systematic review and meta-analysis of individual participant data', source: 'BMJ', year: '2017' },
      { title: 'Vitamin D and risk of cause specific death: systematic review and meta-analysis of observational cohort and randomised intervention studies', source: 'BMJ', year: '2014' },
      { title: 'Supplemental Vitamin D and Incident Fractures in Midlife and Older Adults', source: 'New England Journal of Medicine', year: '2022' },
    ],
    products: [['Vitamin D3 2000 IU', 'Nature Made'], ['Vitamin D-3 5000 IU', 'NOW Foods'], ['Vitamin D-1000', 'Thorne'], ['Vitamin D3 1000 IU', 'Nordic Naturals'], ['Vitamin Code Raw D3', 'Garden of Life']],
  },
  {
    name: 'Magnesium Glycinate', category: 'Mineral', form_type: 'capsule', fda_status: 'approved', safety_status: 'safe', effectivity: 3, safety: 4,
    summary: 'A gentle, well-absorbed form of magnesium often used for relaxation, sleep quality and muscle recovery.',
    benefits: ['Supports normal muscle and nerve function', 'May improve sleep quality and relaxation', 'Gentle on digestion compared with magnesium oxide or citrate', 'Contributes to energy metabolism', 'Commonly low in diets rich in processed foods'],
    contraindications: ['Kidney disease or reduced kidney function', 'Myasthenia gravis', 'Very low heart rate or heart block', 'Doses above 350 mg elemental magnesium without medical advice'],
    enhancing: ['Take in the evening for sleep support', 'Pair with vitamin B6', 'Spread doses through the day if digestion is sensitive', 'Combine with vitamin D for bone health'],
    interactions: ['Antibiotics (tetracyclines, quinolones): separate by 2 to 4 hours', 'Bisphosphonates', 'Diuretics', 'Proton pump inhibitors lower magnesium over time'],
    why_consider: 'Many adults do not reach the recommended magnesium intake, and stress, intense training and certain medications increase losses. The glycinate form is popular because it is well tolerated and glycine itself has calming properties.',
    holistic: ['Leafy greens, nuts, seeds and legumes are rich sources', 'Limiting evening screens supports the same sleep goals', 'Hydration and electrolytes matter for cramps', 'Review medication-related losses with a pharmacist'],
    studies: [
      { title: 'The effect of magnesium supplementation on primary insomnia in elderly: A double-blind placebo-controlled clinical trial', source: 'Journal of Research in Medical Sciences', year: '2012' },
      { title: 'Magnesium in Prevention and Therapy', source: 'Nutrients', year: '2015' },
      { title: 'Oral magnesium supplementation improves insulin sensitivity and metabolic control in type 2 diabetic subjects', source: 'Diabetes Care', year: '2003' },
    ],
    products: [['High Absorption Magnesium', "Doctor's Best"], ['Magnesium Glycinate', 'Pure Encapsulations'], ['Magnesium Glycinate 400', 'KAL'], ['Magnesium Bisglycinate', 'Thorne'], ['Magnesium Bisglycinate Powder', 'NOW Foods']],
  },
  {
    name: 'Omega-3 Fish Oil', category: 'Fatty Acid', form_type: 'softgel', fda_status: 'approved', safety_status: 'safe', effectivity: 4, safety: 4,
    summary: 'Concentrated EPA and DHA from fish oil, studied for heart, brain and joint health and for lowering triglycerides.',
    benefits: ['Supports cardiovascular health and healthy triglyceride levels', 'DHA is a key structural fat in the brain and retina', 'May ease joint stiffness in inflammatory conditions', 'Supports mood and cognitive health with regular intake', 'Fills the gap for people who rarely eat oily fish'],
    contraindications: ['Fish or shellfish allergy', 'Bleeding disorders or upcoming surgery', 'Atrial fibrillation risk at very high doses: discuss with a cardiologist', 'Vegans and vegetarians should choose algae-based omega-3 instead'],
    enhancing: ['Take with the largest meal of the day', 'Choose products with a third-party purity certificate', 'Store in the fridge to prevent oxidation', 'Target 250 to 1000 mg combined EPA and DHA daily'],
    interactions: ['Anticoagulants and antiplatelet drugs', 'Blood pressure medication (additive effect)', 'Orlistat reduces absorption', 'High-dose vitamin E'],
    why_consider: 'Most people eat far less oily fish than dietary guidelines suggest, so omega-3 intake is often low. Fish oil is among the most researched supplements, with consistent evidence for triglyceride lowering and good overall tolerability.',
    holistic: ['Two portions of oily fish a week provide a similar amount', 'Fewer ultra-processed foods improve the omega-6 to omega-3 ratio', 'Regular aerobic exercise complements cardiovascular benefits', 'Sleep and stress management affect inflammation too'],
    studies: [
      { title: 'Marine n-3 Fatty Acids and Prevention of Cardiovascular Disease and Cancer', source: 'New England Journal of Medicine', year: '2019' },
      { title: 'Cardiovascular Risk Reduction with Icosapent Ethyl for Hypertriglyceridemia', source: 'New England Journal of Medicine', year: '2019' },
      { title: 'Omega-3 fatty acids for the primary and secondary prevention of cardiovascular disease', source: 'Cochrane Database of Systematic Reviews', year: '2020' },
    ],
    products: [['Ultimate Omega', 'Nordic Naturals'], ['Elite Omega-3 Gems', 'Carlson'], ['Ultra Omega-3', 'NOW Foods'], ['Triple Strength Omega-3', 'Sports Research'], ['Wild Alaskan Fish Oil', "Wiley's Finest"]],
  },
  {
    name: 'Probiotic Complex', category: 'Probiotic', form_type: 'capsule', fda_status: 'probably_ok', safety_status: 'safe', effectivity: 3, safety: 4,
    summary: 'Multi-strain live bacteria that support a balanced gut microbiome, digestion and immune resilience.',
    benefits: ['Helps restore gut flora after a course of antibiotics', 'May reduce bloating and irregular digestion', 'Supports immune function via the gut lining', 'Some strains shorten infectious diarrhoea', 'Can support regularity during travel or diet changes'],
    contraindications: ['Severely weakened immune system or chemotherapy', 'Central venous catheters', 'Short bowel syndrome', 'Critically ill patients: hospital guidance only'],
    enhancing: ['Take consistently at the same time each day', 'Pair with prebiotic fibre such as inulin or oats', 'Keep refrigerated if the label requires it', 'Allow 4 weeks before judging results'],
    interactions: ['Antibiotics: separate by at least 2 hours', 'Immunosuppressants', 'Antifungal medication', 'Heavy alcohol use reduces benefit'],
    why_consider: 'Modern diets, stress and antibiotics can all disrupt the gut microbiome. A well-formulated multi-strain probiotic is a low-risk way to support digestion, particularly during and after antibiotic treatment or travel.',
    holistic: ['Fermented foods such as yoghurt, kefir, kimchi and sauerkraut serve the same goal', 'Fibre diversity matters more than any single capsule', 'Sleep and stress strongly influence gut health', 'Chewing slowly and regular meals aid digestion'],
    studies: [
      { title: 'Probiotics for the prevention of Clostridium difficile-associated diarrhea in adults and children', source: 'Cochrane Database of Systematic Reviews', year: '2017' },
      { title: 'Probiotics for the prevention of pediatric antibiotic-associated diarrhea', source: 'Cochrane Database of Systematic Reviews', year: '2019' },
      { title: 'The International Scientific Association for Probiotics and Prebiotics consensus statement on the scope and appropriate use of the term probiotic', source: 'Nature Reviews Gastroenterology & Hepatology', year: '2014' },
    ],
    products: [['Digestive Daily Probiotic', 'Culturelle'], ['Dr. Formulated Probiotics Once Daily', 'Garden of Life'], ['Probiotic Supplement', 'Align'], ['DS-01 Daily Synbiotic', 'Seed'], ['Ultimate Flora', 'Renew Life']],
  },
  {
    name: 'Ashwagandha', category: 'Adaptogen', form_type: 'capsule', fda_status: 'probably_ok', safety_status: 'ok', effectivity: 3, safety: 3,
    summary: 'A traditional Ayurvedic adaptogen studied for stress, sleep quality and cortisol balance.',
    benefits: ['May reduce perceived stress and anxiety scores', 'Can improve sleep onset and quality', 'Studied for modest gains in strength and recovery', 'May support healthy testosterone levels in men', 'Traditionally used to support energy and resilience'],
    contraindications: ['Pregnancy and breastfeeding', 'Autoimmune conditions such as lupus or rheumatoid arthritis', 'Thyroid disorders: may raise thyroid hormone levels', 'Liver disease or a history of drug-induced liver injury', 'Before surgery because of sedative effects'],
    enhancing: ['Use a standardised root extract such as KSM-66 or Sensoril', 'Take in the evening if drowsiness occurs', 'Combine with consistent sleep timing', 'Cycle 8 to 12 weeks on, then reassess'],
    interactions: ['Sedatives and sleep medication', 'Thyroid hormone medication', 'Immunosuppressants', 'Blood sugar and blood pressure medication (additive effects)'],
    why_consider: 'If chronic stress and poor sleep are your main concerns, ashwagandha has some of the better human trial data among herbal adaptogens. Effects are modest and build over several weeks, and it should be paused if any liver symptoms appear.',
    holistic: ['Daily movement, daylight and breath-work lower stress hormones too', 'Caffeine after noon undermines the sleep goal', 'Protein and strength training amplify recovery benefits', 'Track mood and sleep for 6 weeks to judge impact'],
    studies: [
      { title: 'An investigation into the stress-relieving and pharmacological actions of an ashwagandha (Withania somnifera) extract', source: 'Medicine (Baltimore)', year: '2019' },
      { title: 'Efficacy and Safety of Ashwagandha (Withania somnifera) Root Extract in Insomnia and Anxiety: A Double-blind, Randomized, Placebo-controlled Study', source: 'Cureus', year: '2019' },
      { title: 'Ashwagandha-induced liver injury: A case series from Iceland and the US Drug-Induced Liver Injury Network', source: 'Liver International', year: '2020' },
    ],
    products: [['KSM-66 Ashwagandha', 'Jarrow Formulas'], ['Ashwagandha Root', 'Gaia Herbs'], ['Organic Ashwagandha', 'Himalaya'], ['Ashwagandha 450 mg', 'NOW Foods'], ['Ashwagandha', "Nature's Way"]],
  },
  {
    name: 'Creatine Monohydrate', category: 'Amino Acid', form_type: 'powder', fda_status: 'approved', safety_status: 'safe', effectivity: 5, safety: 5,
    summary: 'The most researched sports supplement: improves strength and power output and may support brain energy.',
    benefits: ['Increases strength and high-intensity performance', 'Supports lean muscle gain alongside resistance training', 'May improve short-term memory and mental fatigue', 'Helps preserve muscle in older adults', 'Inexpensive with decades of safety data'],
    contraindications: ['Pre-existing kidney disease: medical advice first', 'Bipolar disorder: discuss with a psychiatrist', 'Under 18 without supervision', 'Endurance events in heat without adequate fluid intake'],
    enhancing: ['3 to 5 g daily, no loading phase needed', 'Take with carbohydrates or a meal', 'Stay well hydrated', 'Consistency matters more than timing'],
    interactions: ['NSAIDs and other kidney-stressing drugs', 'Diuretics', 'Very high caffeine doses may blunt the effect', 'Nephrotoxic medication'],
    why_consider: 'Creatine monohydrate has hundreds of trials behind it and is effective for almost everyone who trains, including women and older adults. It also shows emerging benefits for cognition, especially in vegetarians who get little creatine from food.',
    holistic: ['Red meat and fish provide 1 to 2 g per day naturally', 'Progressive strength training turns creatine into results', 'Sleep drives recovery and adaptation', 'A small weight increase from water retention is normal'],
    studies: [
      { title: 'International Society of Sports Nutrition position stand: safety and efficacy of creatine supplementation in exercise, sport, and medicine', source: 'Journal of the International Society of Sports Nutrition', year: '2017' },
      { title: 'Effects of creatine supplementation on cognitive function of healthy individuals: A systematic review of randomized controlled trials', source: 'Experimental Gerontology', year: '2018' },
      { title: 'Creatine Supplementation and Brain Health', source: 'Nutrients', year: '2021' },
    ],
    products: [['Micronized Creatine Powder', 'Optimum Nutrition'], ['Creatine', 'Thorne'], ['Klean Creatine', 'Klean Athlete'], ['Creatine Monohydrate', 'BulkSupplements'], ['Creatine Monohydrate', 'Myprotein']],
  },
  {
    name: 'Vitamin B12', category: 'Vitamin', form_type: 'tablet', fda_status: 'approved', safety_status: 'safe', effectivity: 4, safety: 5,
    summary: 'Essential for red blood cells, nerve function and energy metabolism, and a must-have on vegan and plant-based diets.',
    benefits: ['Prevents B12 deficiency anaemia', 'Supports nerve health and cognition', 'Helps convert food into energy', 'Essential on vegan and vegetarian diets', 'Absorption declines with age, so supplementation helps older adults'],
    contraindications: ['Leber hereditary optic neuropathy', 'Cobalt or cobalamin allergy', 'Unexplained anaemia should be investigated before supplementing', 'Kidney disease with high-dose cyanocobalamin: prefer methylcobalamin'],
    enhancing: ['Sublingual tablets help if stomach acid is low', 'Take with folate and B6 for homocysteine support', 'A daily low dose or a weekly higher dose both work', 'Check blood levels if fatigue persists'],
    interactions: ['Metformin lowers B12 absorption', 'Proton pump inhibitors and H2 blockers', 'Colchicine', 'Nitrous oxide inactivates B12'],
    why_consider: 'Vitamin B12 is found almost exclusively in animal foods, so anyone eating mostly plants should supplement it. Deficiency develops slowly and can cause fatigue, tingling and memory issues that are easy to prevent.',
    holistic: ['Eggs, dairy, fish and fortified plant milks are dietary sources', 'Energy also depends on iron, sleep and hydration', 'Regular blood tests on long-term metformin', 'Pair with a balanced B-complex if the diet is restricted'],
    studies: [
      { title: 'Vitamin B12 deficiency', source: 'BMJ', year: '2014' },
      { title: 'Oral vitamin B12 versus intramuscular vitamin B12 for vitamin B12 deficiency', source: 'Cochrane Database of Systematic Reviews', year: '2018' },
      { title: 'How prevalent is vitamin B12 deficiency among vegetarians?', source: 'Nutrition Reviews', year: '2013' },
    ],
    products: [['Methyl B-12 1000 mcg', 'Jarrow Formulas'], ['Vitamin B12 1000 mcg', 'Nature Made'], ['Vitamin Code Raw B-12', 'Garden of Life'], ['Methylcobalamin 1000 mcg', 'Solgar'], ['Methyl B-12', 'NOW Foods']],
  },
  {
    name: 'Zinc Picolinate', category: 'Mineral', form_type: 'capsule', fda_status: 'approved', safety_status: 'ok', effectivity: 3, safety: 3,
    summary: 'A well-absorbed zinc form that supports immune defence, skin health and wound healing.',
    benefits: ['Supports normal immune function', 'Involved in skin repair and acne management', 'Supports taste, smell and appetite', 'Needed for testosterone production and fertility', 'May shorten the common cold when started early'],
    contraindications: ['Haemochromatosis or copper deficiency', 'Long-term doses above 40 mg daily', 'Pregnancy at high doses', 'Nausea on an empty stomach: take with food'],
    enhancing: ['Take with food to avoid nausea', 'Balance with 1 to 2 mg copper for long-term use', 'Avoid taking with high-phytate meals', 'Short courses during infections, lower doses long term'],
    interactions: ['Antibiotics (quinolones, tetracyclines): separate by 2 hours', 'Penicillamine', 'Diuretics increase zinc loss', 'Iron and calcium supplements compete for absorption'],
    why_consider: 'Zinc requirements rise with intense training, vegetarian diets and periods of illness, and mild shortfalls are common. The picolinate form is well absorbed, making it a sensible choice for short immune-support courses.',
    holistic: ['Oysters, red meat, pumpkin seeds and legumes are good sources', 'Sleep and hand hygiene remain the first line of immune defence', 'Skin health also depends on hydration and sun protection', 'Avoid megadoses: more is not better with zinc'],
    studies: [
      { title: 'Zinc for the common cold', source: 'Cochrane Database of Systematic Reviews', year: '2013' },
      { title: 'Zinc in Human Health: Effect of Zinc on Immune Cells', source: 'Molecular Medicine', year: '2008' },
      { title: 'Discovery of human zinc deficiency: its impact on human health and disease', source: 'Advances in Nutrition', year: '2013' },
    ],
    products: [['Zinc Picolinate 30 mg', 'Thorne'], ['Zinc Picolinate 50 mg', 'NOW Foods'], ['Zinc Picolinate 22 mg', 'Solgar'], ['Zinc 30', 'Pure Encapsulations'], ['Zinc Picolinate', "Nature's Way"]],
  },
];
